-- Seed data for Cyber Crime Laws
-- Pakistan Prevention of Electronic Crimes Act (PECA) 2016

INSERT INTO laws (category, section, title, description, punishment, relevant_pepa_sections) VALUES
('Unauthorized Access', '13', 'Unauthorized access to information system', 'Whoever intentionally accesses or causes access to any information system without lawful authority or exceeds authorized access, or obtains access through fraudulent means, shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 13'),
('Data Damage', '14', 'Damage to information system or data', 'Whoever intentionally and without authorization damages or causes to be damaged, or destroys or causes to be destroyed, or alters or causes to be altered, or disrupts or causes to be disrupted, any information system or data shall be punished with imprisonment for a term which may extend to five years or with fine which may extend to ten million rupees or with both.', 'Imprisonment up to 5 years or fine up to Rs. 10 million or both', 'PECA Section 14'),
('System Interference', '15', 'Interference with information system', 'Whoever intentionally and without authorization interferes with or disrupts or causes to be interfered with or disrupted, any information system shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 15'),
('Cyberstalking', '20', 'Cyberstalking', 'Whoever uses information system to stalk or harass another person shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to one million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 1 million or both', 'PECA Section 20'),
('Phishing', '21', 'Fraudulent use of information system', 'Whoever uses information system to deceive or mislead any person or cause harm to any person through fraudulent means shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 21'),
('Child Pornography', '22', 'Distribution of indecent material to children', 'Whoever intentionally distributes or transmits or causes to be distributed or transmitted any indecent material to a child shall be punished with imprisonment for a term which may extend to seven years or with fine which may extend to twenty million rupees or with both.', 'Imprisonment up to 7 years or fine up to Rs. 20 million or both', 'PECA Section 22'),
('Identity Theft', '23', 'Electronic forgery', 'Whoever intentionally and without authorization alters or forges or causes to be altered or forged any electronic record or electronic signature shall be punished with imprisonment for a term which may extend to five years or with fine which may extend to ten million rupees or with both.', 'Imprisonment up to 5 years or fine up to Rs. 10 million or both', 'PECA Section 23'),
('Hacking', '16', 'Hacking or unauthorized access with intent to commit further offences', 'Whoever intentionally accesses or causes access to any information system without lawful authority with intent to commit any of the offences under this Act shall be punished with imprisonment for a term which may extend to seven years or with fine which may extend to twenty million rupees or with both.', 'Imprisonment up to 7 years or fine up to Rs. 20 million or both', 'PECA Section 16'),
('Malware', '17', 'Making, possessing or distributing malware', 'Whoever makes, possesses or distributes malware shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 17'),
('Data Theft', '18', 'Electronic theft of data', 'Whoever intentionally accesses or causes access to any information system without lawful authority and obtains any data shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 18'),
('Spamming', '19', 'Electronic spam', 'Whoever intentionally sends electronic spam shall be punished with fine which may extend to fifty thousand rupees.', 'Fine up to Rs. 50,000', 'PECA Section 19'),
('Online Harassment', '20', 'Cyber harassment', 'Whoever uses information system to harass, intimidate or threaten any person shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to one million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 1 million or both', 'PECA Section 20'),
('Financial Fraud', '24', 'Electronic fraud', 'Whoever uses information system to commit fraud shall be punished with imprisonment for a term which may extend to seven years or with fine which may extend to twenty million rupees or with both.', 'Imprisonment up to 7 years or fine up to Rs. 20 million or both', 'PECA Section 24'),
('Privacy Violation', '25', 'Violation of privacy', 'Whoever intentionally violates the privacy of any person by unauthorized access to or disclosure of any personal data shall be punished with imprisonment for a term which may extend to three years or with fine which may extend to five million rupees or with both.', 'Imprisonment up to 3 years or fine up to Rs. 5 million or both', 'PECA Section 25'),
('Critical Infrastructure', '26', 'Attacks on critical infrastructure', 'Whoever intentionally attacks or causes to be attacked any critical infrastructure through information system shall be punished with imprisonment for a term which may extend to ten years or with fine which may extend to fifty million rupees or with both.', 'Imprisonment up to 10 years or fine up to Rs. 50 million or both', 'PECA Section 26')
ON CONFLICT DO NOTHING;